### GENERAL SETTINGS ###

# Site settings
title: THE SURFING CODER
description: "Thoughts and ramblings from a software engineer who also likes to shred the occaisonal gnar."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    #- Some Ave, 987,
    #- 23890, New York,
    #- United States.
    - Indialantic, FL
    - United States
email: surfingcoder@gmail.com
tel: 321-984-6007


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult. --C.A.R. Hoare"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "I love solving complex problems with well-architected software solutions. It can be incredibly rewarding to craft an intricate design and watch it mature into something great.  I'm passionate about software engineering,  design and management techniques that produce reliable, robust software that is pleasurable to maintain and satisfying to use. Most recently I have enjoyed prototyping and creating new user interface designs and blurring the line between developer and graphic designer."
    author: Jason Carlton
    position: SOFTWARE ENGINEER
